name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        run: pipx run cibuildwheel==2.12.0

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
